name: Rector

on:
  pull_request:
    branches:
      - 1.x
    paths:
      - '**.php'
      - 'composer.**'
      - 'rector.php'
      - '.github/workflows/rector.yml'
  push:
    branches:
      - 1.x
    paths:
      - '**.php'
      - 'composer.**'
      - 'rector.php'
      - '.github/workflows/rector.yml'

jobs:
  build:
    name: PHP ${{ matrix.php-versions }} Rector Analysis
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0', '8.1', '8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpstan
          extensions: intl, json, mbstring, xml
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        run: echo "COMPOSER_CACHE_FILES_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_CACHE_FILES_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer -q config -g github-oauth.github.com "${{ secrets.GITHUB_TOKEN }}"
          if [ -f composer.lock ]; then
            composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
          else
            composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader
          fi

      - name: Analyze for refactoring
        run: vendor/bin/rector process --dry-run --no-progress-bar
